# Chapter 6 - Building Your First Deep Neural Network: Introduction to Backpropagation

## Tujuan Pembelajaran

Pada chapter ini kita mulai membangun neural network yang memiliki lebih dari satu layer.

Kita akan mempelajari:

- Neural network
- Hidden layer
- Forward propagation
- Error
- Backpropagation
- Delta
- Weight update

Konsep utama chapter ini adalah bagaimana error dari output dapat digunakan untuk memperbaiki weight pada layer sebelumnya.

## 1. Struktur Neural Network

Neural network sederhana dapat terdiri dari:

Input → Hidden Layer → Output

Input memberikan informasi kepada hidden layer.

Hidden layer kemudian menghasilkan nilai baru yang digunakan oleh output layer.

Karena terdapat lebih dari satu layer, proses pembelajaran menjadi lebih kompleks dibandingkan model sebelumnya.

In [1]:
import numpy as np

# Input
input_data = np.array([0.8, 0.1, 0.9])

# Weight dari input ke hidden layer
weights_0 = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9]
])

# Weight dari hidden layer ke output
weights_1 = np.array([0.2, 0.4, 0.6])

## 2. Forward Propagation

Forward propagation adalah proses ketika data bergerak dari input menuju output.

Prosesnya:

Input
↓
Hidden Layer
↓
Output

Pada hidden layer, input dikalikan dengan weight.

Kemudian hasilnya diteruskan ke output layer.

In [2]:
# Forward propagation ke hidden layer
hidden = np.dot(input_data, weights_0)

# Forward propagation ke output
prediction = np.dot(hidden, weights_1)

print("Hidden layer:", hidden)
print("Prediction:", prediction)

Hidden layer: [0.75 0.93 1.11]
Prediction: 1.1880000000000002


## 3. Menghitung Error

Setelah mendapatkan prediction, kita membandingkannya dengan target.

Misalnya:

target = 1

Kemudian kita menggunakan squared error:

error = (prediction - target)²

In [3]:
target = 1.0

error = (prediction - target) ** 2

print("Prediction:", prediction)
print("Target:", target)
print("Error:", error)

Prediction: 1.1880000000000002
Target: 1.0
Error: 0.03534400000000006


## 4. Apa Itu Backpropagation?

Backpropagation adalah proses mengirim informasi error dari output kembali menuju layer sebelumnya.

Tujuannya adalah menentukan bagaimana setiap weight harus diubah.

Secara sederhana:

Forward propagation:
Input → Hidden → Output

Backpropagation:
Output → Hidden → Input

Dengan backpropagation, setiap weight dapat mengetahui seberapa besar kontribusinya terhadap error.

## 5. Menghitung Delta Output

Pertama kita menghitung delta pada output.

Untuk squared error, kita dapat menggunakan:

delta_output = prediction - target

Nilai delta menunjukkan seberapa jauh prediction dari target.

Jika prediction terlalu besar, weight perlu dikurangi.

Jika prediction terlalu kecil, weight perlu ditambah.

In [4]:
delta_output = prediction - target

print("Output delta:", delta_output)

Output delta: 0.18800000000000017


## 6. Menghitung Gradient Output Layer

Gradient pada weight output dipengaruhi oleh:

- nilai hidden layer
- delta output

Secara sederhana:

gradient = hidden × delta_output

Gradient ini kemudian digunakan untuk memperbarui weight output.

In [5]:
learning_rate = 0.1

# Gradient untuk weight output
gradient_output = hidden * delta_output

# Update weight output
weights_1 = weights_1 - learning_rate * gradient_output

print("Updated output weights:")
print(weights_1)

Updated output weights:
[0.1859   0.382516 0.579132]


## 7. Mengirim Error ke Hidden Layer

Sekarang kita perlu mengetahui kontribusi hidden layer terhadap error.

Informasi error dari output dikirim kembali menggunakan weight dari output layer.

Secara sederhana:

hidden_delta = output_delta × output_weights

Kemudian nilai tersebut digunakan untuk memperbaiki weight dari input menuju hidden layer.

In [6]:
# Menggunakan weight output sebelum update untuk menghitung hidden delta
old_weights_1 = np.array([0.2, 0.4, 0.6])

hidden_delta = delta_output * old_weights_1

print("Hidden delta:")
print(hidden_delta)

Hidden delta:
[0.0376 0.0752 0.1128]


## 8. Update Weight pada Hidden Layer

Setelah mendapatkan hidden delta, kita dapat menghitung gradient untuk weight dari input ke hidden layer.

Gradient dihitung berdasarkan:

input × hidden_delta

Kemudian weight diperbarui menggunakan learning rate.

In [7]:
# Gradient untuk weight input → hidden
gradient_hidden = np.outer(input_data, hidden_delta)

# Update weights
weights_0 = weights_0 - learning_rate * gradient_hidden

print("Updated input-to-hidden weights:")
print(weights_0)

Updated input-to-hidden weights:
[[0.096992 0.193984 0.290976]
 [0.399624 0.499248 0.598872]
 [0.696616 0.793232 0.889848]]


## 9. Training Neural Network

Sekarang seluruh proses dapat dilakukan berulang kali.

Pada setiap iterasi:

1. Input masuk ke neural network.
2. Forward propagation menghasilkan prediction.
3. Error dihitung.
4. Backpropagation menghitung delta.
5. Gradient dihitung.
6. Weight diperbarui.
7. Proses diulang.

Dengan melakukan training berkali-kali, neural network akan mencoba menghasilkan prediction yang semakin dekat dengan target.

In [8]:
import numpy as np

# Data
inputs = np.array([0.8, 0.1, 0.9])
target = 1.0

# Weight awal
weights_0 = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9]
])

weights_1 = np.array([0.2, 0.4, 0.6])

learning_rate = 0.05

for i in range(50):

    # =========================
    # FORWARD PROPAGATION
    # =========================

    hidden = np.dot(inputs, weights_0)

    prediction = np.dot(hidden, weights_1)

    # =========================
    # ERROR
    # =========================

    error = (prediction - target) ** 2

    # =========================
    # BACKPROPAGATION
    # =========================

    delta_output = prediction - target

    # Simpan weight output sebelum di-update
    old_weights_1 = weights_1.copy()

    # Gradient output layer
    gradient_output = hidden * delta_output

    # Hidden delta
    hidden_delta = delta_output * old_weights_1

    # Gradient hidden layer
    gradient_hidden = np.outer(inputs, hidden_delta)

    # =========================
    # UPDATE WEIGHTS
    # =========================

    weights_1 = weights_1 - learning_rate * gradient_output

    weights_0 = weights_0 - learning_rate * gradient_hidden

    if i % 5 == 0:
        print(
            f"Iterasi {i+1}: "
            f"Prediction = {prediction:.4f}, "
            f"Error = {error:.6f}"
        )

Iterasi 1: Prediction = 1.1880, Error = 0.035344
Iterasi 6: Prediction = 1.0750, Error = 0.005621
Iterasi 11: Prediction = 1.0313, Error = 0.000977
Iterasi 16: Prediction = 1.0133, Error = 0.000176
Iterasi 21: Prediction = 1.0057, Error = 0.000032
Iterasi 26: Prediction = 1.0024, Error = 0.000006
Iterasi 31: Prediction = 1.0010, Error = 0.000001
Iterasi 36: Prediction = 1.0004, Error = 0.000000
Iterasi 41: Prediction = 1.0002, Error = 0.000000
Iterasi 46: Prediction = 1.0001, Error = 0.000000


## 10. Melihat Hasil Akhir

Setelah proses training selesai, kita dapat melakukan forward propagation sekali lagi untuk melihat hasil akhirnya.

In [ ]:
# Forward propagation setelah training

hidden = np.dot(inputs, weights_0)
prediction = np.dot(hidden, weights_1)

error = (prediction - target) ** 2

print("Final prediction:", prediction)
print("Target:", target)
print("Final error:", error)

## Kesimpulan Chapter 6

Pada chapter ini kita membuat neural network yang memiliki lebih dari satu layer.

Konsep penting yang dipelajari:

- Neural network dapat memiliki hidden layer.
- Forward propagation digunakan untuk menghasilkan prediction.
- Error digunakan untuk mengetahui seberapa buruk prediction.
- Backpropagation mengirim informasi error kembali ke layer sebelumnya.
- Gradient digunakan untuk menentukan perubahan weight.
- Weight diperbarui menggunakan gradient descent.
- Training dilakukan berulang kali agar prediction menjadi semakin baik.

Backpropagation merupakan salah satu konsep paling penting dalam deep learning karena memungkinkan neural network dengan banyak layer untuk belajar dari error.